"""Fix gmail multi-tenancy

Revision ID: ebd0094234a4
Revises: 007
Create Date: 2026-05-09 10:14:33.200906
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ebd0094234a4'
down_revision: Union[str, None] = '007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agents', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('agents', 'max_concurrent_tasks',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint('agents_name_key', 'agents', type_='unique')
    op.drop_index('ix_agents_name', table_name='agents')
    op.create_index(op.f('ix_agents_name'), 'agents', ['name'], unique=True)
    op.alter_column('approvals', 'status',
               existing_type=postgresql.ENUM('pending_approval', 'approved', 'edited', 'rejected', 'expired', name='approval_status_enum'),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_approvals_created_at'), 'approvals', ['created_at'], unique=False)
    op.add_column('email_messages', sa.Column('user_id', sa.Uuid(), nullable=False))
    op.create_index(op.f('ix_email_messages_user_id'), 'email_messages', ['user_id'], unique=False)
    op.create_foreign_key(None, 'email_messages', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('email_threads', sa.Column('user_id', sa.Uuid(), nullable=False))
    op.create_index(op.f('ix_email_threads_user_id'), 'email_threads', ['user_id'], unique=False)
    op.create_foreign_key(None, 'email_threads', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('ingestion_logs', sa.Column('user_id', sa.Uuid(), nullable=False))
    op.create_index(op.f('ix_ingestion_logs_user_id'), 'ingestion_logs', ['user_id'], unique=False)
    op.create_foreign_key(None, 'ingestion_logs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('logs', 'level',
               existing_type=postgresql.ENUM('debug', 'info', 'warning', 'error', 'critical', name='log_level_enum'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('logs', 'metadata_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('logs', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.add_column('oauth_tokens', sa.Column('user_id', sa.Uuid(), nullable=False))
    op.drop_index('ix_oauth_tokens_provider', table_name='oauth_tokens')
    op.create_index(op.f('ix_oauth_tokens_provider'), 'oauth_tokens', ['provider'], unique=False)
    op.create_index(op.f('ix_oauth_tokens_user_id'), 'oauth_tokens', ['user_id'], unique=False)
    op.create_unique_constraint('uq_user_provider', 'oauth_tokens', ['user_id', 'provider'])
    op.create_foreign_key(None, 'oauth_tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('tasks', 'retry_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('tasks', 'status',
               existing_type=postgresql.ENUM('pending', 'queued', 'in_progress', 'processing', 'awaiting_approval', 'completed', 'failed', 'retrying', 'cancelled', name='task_status_enum'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('tasks', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_tool_execution_logs_created_at'), 'tool_execution_logs', ['created_at'], unique=False)
    op.alter_column('users', 'is_gmail_connected',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=False)
    op.alter_column('users', 'has_completed_onboarding',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=False)
    op.alter_column('users', 'onboarding_step',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               nullable=False)
    op.alter_column('users', 'preferences',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               nullable=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               nullable=True)
    op.alter_column('users', 'preferences',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               existing_nullable=True)
    op.alter_column('users', 'onboarding_step',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'welcome'::character varying"),
               nullable=True)
    op.alter_column('users', 'has_completed_onboarding',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               nullable=True)
    op.alter_column('users', 'is_gmail_connected',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               nullable=True)
    op.drop_index(op.f('ix_tool_execution_logs_created_at'), table_name='tool_execution_logs')
    op.alter_column('tasks', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('tasks', 'status',
               existing_type=postgresql.ENUM('pending', 'queued', 'in_progress', 'processing', 'awaiting_approval', 'completed', 'failed', 'retrying', 'cancelled', name='task_status_enum'),
               server_default=sa.text("'pending'::task_status_enum"),
               existing_nullable=False)
    op.alter_column('tasks', 'retry_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.drop_constraint(None, 'oauth_tokens', type_='foreignkey')
    op.drop_constraint('uq_user_provider', 'oauth_tokens', type_='unique')
    op.drop_index(op.f('ix_oauth_tokens_user_id'), table_name='oauth_tokens')
    op.drop_index(op.f('ix_oauth_tokens_provider'), table_name='oauth_tokens')
    op.create_index('ix_oauth_tokens_provider', 'oauth_tokens', ['provider'], unique=True)
    op.drop_column('oauth_tokens', 'user_id')
    op.alter_column('logs', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('logs', 'metadata_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('logs', 'level',
               existing_type=postgresql.ENUM('debug', 'info', 'warning', 'error', 'critical', name='log_level_enum'),
               server_default=sa.text("'info'::log_level_enum"),
               existing_nullable=False)
    op.drop_constraint(None, 'ingestion_logs', type_='foreignkey')
    op.drop_index(op.f('ix_ingestion_logs_user_id'), table_name='ingestion_logs')
    op.drop_column('ingestion_logs', 'user_id')
    op.drop_constraint(None, 'email_threads', type_='foreignkey')
    op.drop_index(op.f('ix_email_threads_user_id'), table_name='email_threads')
    op.drop_column('email_threads', 'user_id')
    op.drop_constraint(None, 'email_messages', type_='foreignkey')
    op.drop_index(op.f('ix_email_messages_user_id'), table_name='email_messages')
    op.drop_column('email_messages', 'user_id')
    op.drop_index(op.f('ix_approvals_created_at'), table_name='approvals')
    op.alter_column('approvals', 'status',
               existing_type=postgresql.ENUM('pending_approval', 'approved', 'edited', 'rejected', 'expired', name='approval_status_enum'),
               server_default=sa.text("'pending_approval'::approval_status_enum"),
               existing_nullable=False)
    op.drop_index(op.f('ix_agents_name'), table_name='agents')
    op.create_index('ix_agents_name', 'agents', ['name'], unique=False)
    op.create_unique_constraint('agents_name_key', 'agents', ['name'])
    op.alter_column('agents', 'max_concurrent_tasks',
               existing_type=sa.INTEGER(),
               server_default=sa.text('5'),
               existing_nullable=False)
    op.alter_column('agents', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    # ### end Alembic commands ###
